apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: log-pv-claim
      containers:
        - name: log-writer
          image: kontrakti/log-writer:latest
          volumeMounts: 
          - name: shared-log
            mountPath: /logs
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        - name: log-reader
          image: kontrakti/log-reader:latest
          env: 
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts: 
          - name: shared-log
            mountPath: /logs
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
