apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  namespace: applications
spec:
  storageClassName: log-pv-cn 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi