apiVersion: v1
kind: PersistentVolume
metadata:
  name: ping-log-pv
  namespace: applications
spec:
  storageClassName: ping-log-pv-cn 
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/ping-log-pv
  nodeAffinity: 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0