apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: applications
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "16"
    limits.memory: 16Gi
