apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-log-pv-claim
spec:
  storageClassName: ping-log-pv-cn 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi