apiVersion: apps/v1
kind: Deployment 
metadata:
  name: to-do-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-backend
  template:
    metadata:
      labels:
        app: to-do-backend
    spec:
      containers:
        - name: to-do-backend
          image: kontrakti/to-do-backend:latest
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"